# Service name
spring:
  application:
    name: restaurant-service

# Spring Server setup
server:
  address: 0.0.0.0
  port: ${DATA_SERVICE_PORT}
  compression:
    enabled: true
  http2:
    enabled: true

# Eureka configuration
eureka:
  client:
    serviceUrl:
      defaultZone: http://${DISCOVERY_HOST:localhost}:${DISCOVERY_PORT:8761}/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: ${SERVICE_HOST:localhost}
    prefer-ip-address: false
