version: '3'

services:

  app:
    container_name: app
    image: eliottclavier/tripi-app:latest
    command: /bin/bash -c "envsubst '$${APP_PORT},$${GATEWAY_PORT}' < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf && nginx -g 'daemon off;'"
    restart: unless-stopped
    env_file:
      - ./env/app.env
    environment:
      APP_PORT: ${APP_PORT}
      GATEWAY_PORT: ${GATEWAY_PORT}
      VIRTUAL_HOST: ${APP_VIRTUAL_HOST}
      VIRTUAL_PORT: ${APP_PORT}
      LETSENCRYPT_HOST: ${APP_VIRTUAL_HOST}
    expose:
      - "${APP_PORT}"
    volumes:
      - ./front/nginx.conf:/etc/nginx/nginx.conf.template
    networks:
      - front-net
      - nginx-proxy
    depends_on:
      - gateway
      - discovery

  gateway:
    container_name: gateway
    image: eliottclavier/tripi-gateway:latest
    restart: unless-stopped
    env_file:
      - ./env/gateway.env
      - ./env/discovery.env
      - ./env/app.env
      - ./env/database.env
    environment:
      VIRTUAL_HOST: ${GATEWAY_VIRTUAL_HOST}
      VIRTUAL_PORT: ${GATEWAY_PORT}
      LETSENCRYPT_HOST: ${GATEWAY_VIRTUAL_HOST}
    expose:
      - "${GATEWAY_PORT}"
    networks:
      - front-net
      - back-net
      - nginx-proxy
    depends_on:
      - database

  discovery:
    container_name: discovery
    image: eliottclavier/tripi-discovery:latest
    restart: unless-stopped
    env_file:
      - ./env/discovery.env
    expose:
      - "${DISCOVERY_PORT}"
    networks:
      - back-net

  database:
    container_name: database
    image: mariadb:latest
    restart: unless-stopped
    env_file:
      - ./env/database.env
    volumes:
      - /data/database:/var/lib/mysql
    expose:
      - "${MARIADB_PORT}"
    networks:
      - back-net

volumes:
  database:
  nginx.conf:

networks:
  front-net:
  back-net:
  nginx-proxy:
    external:
      name: nginx-proxy