version: '3'

services:

  app:
    container_name: app
    image: eliottclavier/tripi-app:latest
    command: /bin/bash -c "envsubst '$${APP_PORT},$${GATEWAY_PORT}' < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf && nginx -g 'daemon off;'"
    restart: unless-stopped
    env_file:
      - ./env/app.env
    environment:
      APP_PORT: ${APP_PORT}
      GATEWAY_PORT: ${GATEWAY_PORT}
      VIRTUAL_HOST: ${APP_VIRTUAL_HOST}
      VIRTUAL_PORT: ${APP_PORT}
      LETSENCRYPT_HOST: ${APP_VIRTUAL_HOST}
    expose:
      - "${APP_PORT}"
    volumes:
      - ./front/nginx.conf:/etc/nginx/nginx.conf.template
    networks:
      - front-net
      - nginx-proxy
    depends_on:
      - gateway
      - discovery

  gateway:
    container_name: gateway
    image: eliottclavier/tripi-gateway:latest
    restart: unless-stopped
    command: /bin/bash -c "java $${JAVA_OPTS} -jar /gateway.jar"
    env_file:
      - ./env/gateway.env
      - ./env/app.env
    environment:
      VIRTUAL_HOST: ${GATEWAY_VIRTUAL_HOST}
      VIRTUAL_PORT: ${GATEWAY_PORT}
      LETSENCRYPT_HOST: ${GATEWAY_VIRTUAL_HOST}
      JAVA_OPTS: "-DGATEWAY_PORT=${GATEWAY_PORT} -DDISCOVERY_HOST=${DISCOVERY_HOST} -DDISCOVERY_PORT=${DISCOVERY_PORT}"
    expose:
      - "${GATEWAY_PORT}"
    networks:
      - front-net
      - gateway-net
      - nginx-proxy
    depends_on:
      - database
      - discovery

  discovery:
    container_name: discovery
    image: eliottclavier/tripi-discovery:latest
    restart: unless-stopped
    command: /bin/bash -c "java $${JAVA_OPTS} -jar /discovery.jar"
    environment:
      VIRTUAL_HOST: ${DISCOVERY_VIRTUAL_HOST}
      VIRTUAL_PORT: ${DISCOVERY_PORT}
      LETSENCRYPT_HOST: ${DISCOVERY_VIRTUAL_HOST}
      JAVA_OPTS: "-DDISCOVERY_HOST=localhost -DDISCOVERY_PORT=${DISCOVERY_PORT}"
    expose:
      - "${DISCOVERY_PORT}"
    networks:
      - gateway-net
      - services-net
      - nginx-proxy

  database:
    container_name: database
    image: mariadb:latest
    restart: unless-stopped
    env_file:
      - ./env/database.env
    volumes:
      - /data/database:/var/lib/mysql
    expose:
      - "${MARIADB_PORT}"
    networks:
      - database-net

  # Data services
  accommodation:
    container_name: accommodation
    image: eliottclavier/tripi-accommodation:latest
    restart: unless-stopped
    command: /bin/bash -c "java $${JAVA_OPTS} -jar /accommocation.jar"
    environment:
      JAVA_OPTS: "-DDISCOVERY_HOST=${DISCOVERY_HOST} -DDISCOVERY_PORT=${DISCOVERY_PORT} -DDATA_SERVICE_PORT=${DATA_SERVICE_PORT}"
    expose:
      - "${DATA_SERVICE_PORT}"
    networks:
      - services-net
    depends_on:
      - discovery

  activity:
    container_name: activity
    image: eliottclavier/tripi-activity:latest
    restart: unless-stopped
    command: /bin/bash -c "java $${JAVA_OPTS} -jar /activity.jar"
    environment:
      JAVA_OPTS: "-DDISCOVERY_HOST=${DISCOVERY_HOST} -DDISCOVERY_PORT=${DISCOVERY_PORT} -DDATA_SERVICE_PORT=${DATA_SERVICE_PORT}"
    expose:
      - "${DATA_SERVICE_PORT}"
    networks:
      - services-net
    depends_on:
      - discovery

  bar:
    container_name: bar
    image: eliottclavier/tripi-bar:latest
    restart: unless-stopped
    command: /bin/bash -c "java $${JAVA_OPTS} -jar /bar.jar"
    environment:
      JAVA_OPTS: "-DDISCOVERY_HOST=${DISCOVERY_HOST} -DDISCOVERY_PORT=${DISCOVERY_PORT} -DDATA_SERVICE_PORT=${DATA_SERVICE_PORT}"
    expose:
      - "${DATA_SERVICE_PORT}"
    networks:
      - services-net
    depends_on:
      - discovery

  restaurant:
    container_name: restaurant
    image: eliottclavier/tripi-restaurant:latest
    restart: unless-stopped
    command: /bin/bash -c "java $${JAVA_OPTS} -jar /restaurant.jar"
    environment:
      JAVA_OPTS: "-DDISCOVERY_HOST=${DISCOVERY_HOST} -DDISCOVERY_PORT=${DISCOVERY_PORT} -DDATA_SERVICE_PORT=${DATA_SERVICE_PORT}"
    expose:
      - "${DATA_SERVICE_PORT}"
    networks:
      - services-net
    depends_on:
      - discovery

  transport:
    container_name: transport
    image: eliottclavier/tripi-transport:latest
    restart: unless-stopped
    command: /bin/bash -c "java $${JAVA_OPTS} -jar /transport.jar"
    environment:
      JAVA_OPTS: "-DDISCOVERY_HOST=${DISCOVERY_HOST} -DDISCOVERY_PORT=${DISCOVERY_PORT} -DDATA_SERVICE_PORT=${DATA_SERVICE_PORT}"
    expose:
      - "${DATA_SERVICE_PORT}"
    networks:
      - services-net
    depends_on:
      - discovery

  trip:
    container_name: trip
    image: eliottclavier/tripi-trip:latest
    restart: unless-stopped
    command: /bin/bash -c "java $${JAVA_OPTS} -jar /trip.jar"
    environment:
      JAVA_OPTS: "-DDISCOVERY_HOST=${DISCOVERY_HOST} -DDISCOVERY_PORT=${DISCOVERY_PORT} -DDATA_SERVICE_PORT=${DATA_SERVICE_PORT} -DMARIADB_HOST=${MARIADB_HOST} -DMARIADB_PORT=${MARIADB_PORT} -DMARIADB_DATABASE=${MARIADB_DATABASE} -DMYSQL_USER=${MYSQL_USER} -DMYSQL_PASSWORD=${MYSQL_PASSWORD}"
    expose:
      - "${DATA_SERVICE_PORT}"
    networks:
      - services-net
      - database-net
    depends_on:
      - discovery
      - database

  user:
    container_name: user
    image: eliottclavier/tripi-user:latest
    restart: unless-stopped
    command: /bin/bash -c "java $${JAVA_OPTS} -jar /user.jar"
    environment:
      JAVA_OPTS: "-DDISCOVERY_HOST=${DISCOVERY_HOST} -DDISCOVERY_PORT=${DISCOVERY_PORT} -DDATA_SERVICE_PORT=${DATA_SERVICE_PORT} -DMARIADB_HOST=${MARIADB_HOST} -DMARIADB_PORT=${MARIADB_PORT} -DMARIADB_DATABASE=${MARIADB_DATABASE} -DMYSQL_USER=${MYSQL_USER} -DMYSQL_PASSWORD=${MYSQL_PASSWORD}"
    expose:
      - "${DATA_SERVICE_PORT}"
    networks:
      - services-net
      - database-net
    depends_on:
      - discovery
      - database


volumes:
  database:
  nginx.conf:

networks:
  front-net:
  gateway-net:
  services-net:
  database-net:
  nginx-proxy:
    external:
      name: nginx-proxy