
# Service name
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  application:
    name: transport-service

# Spring Server setup
server:
  address: ${DATA_SERVICE_HOST:localhost}
  port: ${DATA_SERVICE_PORT:8086}
  compression:
    enabled: true
  http2:
    enabled: true

# Eureka configuration    
eureka:
  client:
    serviceUrl:
      defaultZone: http://${DISCOVERY_HOST:localhost}:${DISCOVERY_PORT:8761}/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: ${SERVICE_HOST:localhost}
    prefer-ip-address: false

 # Amadeus API Configuration
amadeus:
  enabled: true
  apiKey: ${AMADEUS_KEY}
  apiSecret: ${AMADEUS_SECRET}

# Google Configuration
google:
  apiKey: ${GOOGLE_KEY}

# Sources
sources: GOOGLEMAPS,AMADEUS

springdoc:
  swagger-ui:
    path: /transports/swagger-ui/index.html
  api-docs:
    path: /transports/swagger-ui/index.html

