# Service name
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  application:
    name: activity-service
  main:
    allow-bean-definition-overriding: true

# Spring Server setup
server:
  address: ${DATA_SERVICE_HOST:localhost}
  port: ${DATA_SERVICE_PORT:8087}
  compression:
    enabled: true
  http2:
    enabled: true

# Eureka configuration
eureka:
  client:
    serviceUrl:
      defaultZone: http://${DISCOVERY_HOST:localhost}:${DISCOVERY_PORT:8761}/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: ${SERVICE_HOST:localhost}
    prefer-ip-address: false

data:
  actives: ${DATA_ACTIVE:allevents}

springdoc:
  swagger-ui:
    path: /enjoy/swagger-ui/index.html
  api-docs:
    path: /enjoy/swagger-ui/index.html

