server:
  address: ${DATA_SERVICE_HOST:localhost}
  port: ${DATA_SERVICE_PORT:8084}

eureka:
  instance:
    prefer-ip-address: false
    hostname: ${DISCOVERY_HOST:localhost}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${DISCOVERY_HOST:localhost}:${DISCOVERY_PORT:8761}/eureka/

spring:
  application:
    name: location-service
  main:
    allow-bean-definition-overriding: true

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG

data:
  actives: ${DATA_ACTIVE:google-maps}
  sources:
    google-maps:
      api-key: ${GOOGLE_KEY}
  search:
    input:
      limit: 5
  picture:
    width: 400


