server:
  port: ${DISCOVERY_PORT}

eureka:
  instance:
    hostname: ${DISCOVERY_HOST:localhost}
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${DISCOVERY_HOST}:${DISCOVERY_PORT}/eureka/
