server:
  port: ${DISCOVERY_PORT:8761}

eureka:
  instance:
    hostname: ${DISCOVERY_HOST:localhost}
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 5000

spring:
  cloud:
    inetutils:
      preferred-networks: 146.122,10.0

logging:
  level:
    com.netflix.eureka: DEBUG
    com.netflix.discovery: DEBUG
  file:
    name: eureka-server.log


