server:
  port: ${GATEWAY_PORT}

spring:
  main:
    web-application-type: reactive
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
    eureka:
      client:
        serviceUrl:
          defaultZone: http://${DISCOVERY_HOST}:${DISCOVERY_PORT}/eureka/

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true



