server:
  port: ${GATEWAY_PORT}

spring:
  main:
    web-application-type: reactive
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
        defaultZone: http://${DISCOVERY_HOST}:${DISCOVERY_PORT}/eureka/



