server:
  port: 5080

spring:
  main:
    web-application-type: reactive
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
    eureka:
      client:
        serviceUrl:
          defaultZone: http://discovery:8761/eureka/

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true



