export enum LeisureCategory {
  BAR = 'BARS',
  RESTAURANT = 'RESTAURANTS',
  ACCOMMODATION = 'ACCOMMODATIONS',
  CULTURAL_EVENT = 'CULTURAL_EVENT',
  SPORTING_EVENT = 'SPORTING_EVENT',
  UNKNOWN = 'UNKNOWN',
}
