# Service name
spring:
  application:
    name: accommodation-service
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

# Spring Server setup
server:
  address: ${DATA_SERVICE_HOST:localhost}
  port: ${DATA_SERVICE_PORT:8085}
  compression:
    enabled: true
  http2:
    enabled: true

# Eureka configuration
eureka:
  client:
    serviceUrl:
      defaultZone: http://${DISCOVERY_HOST:localhost}:${DISCOVERY_PORT:8761}/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: ${SERVICE_HOST:localhost}
    prefer-ip-address: false

# Google Configuration
google:
  apiKey: ${GOOGLE_KEY}

# Sources
sources: GOOGLEMAPS

springdoc:
  swagger-ui:
    path: /accommodation/swagger-ui/index.html
  api-docs:
    path: /accommodation/swagger-ui/index.html