name: Build and publish App image

on:
  workflow_call:
    inputs:
      context:
        description: 'Docker build context'
        required: true
      dockerfile:
        description: 'Dockerfile path'
        required: true
      image_name:
        description: 'Docker image name'
        required: true
      tag_name:
        description: 'Docker image tag'
        required: true

jobs:
  build_and_push_image:
    uses: ./.github/workflows/build-publish-image.yml
    with:
      context: 'front'
      dockerfile: 'front/Dockerfile'
      image_name: 'tripi-app'
      tag_name: '${{ github.ref_name }}'