name: Build and publish API image

on:
  workflow_call:
    inputs:
      context:
        description: 'Docker build context'
        required: true
        default: '.'
        type: string
      dockerfile:
        description: 'Dockerfile path'
        required: true
        default: './Dockerfile'
        type: string
      image_name:
        description: 'Docker image name'
        required: true
        default: 'tripi-app'
        type: string
      tag_name:
        description: 'Docker image tag'
        required: true
        default: 'latest'
        type: string

jobs:
  build_and_push_image:
    name: Build and publish API Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ${{ github.event.inputs.context }}
          file: ${{ github.event.inputs.dockerfile }}
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.inputs.image_name }}:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.inputs.image_name }}:${{ github.event.inputs.tag_name }}