name: Build and publish App image

on:
  workflow_call:

jobs:
  build_and_push_image:
    uses: ./.github/workflows/build-and-push-image.yml@main
    with:
      context: 'front'
      dockerfile: 'front/Dockerfile'
      image_name: 'tripi-app'
      tag_name: '${{ github.ref_name }}'