name: Build and publish API images

on:
  workflow_call:
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true

jobs:
  build_and_push_gateway_image:
    name: Gateway image
    uses: ./.github/workflows/build-publish-image.yml
    with:
      context: 'back/gateway'
      dockerfile: 'back/gateway/Dockerfile'
      image_name: 'tripi-gateway'
      tag_name: ${{ github.ref_name }}
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  build_and_push_discovery_image:
    name: Discovery image
    uses: ./.github/workflows/build-publish-image.yml
    with:
      context: 'back/discovery'
      dockerfile: 'back/discovery/Dockerfile'
      image_name: 'tripi-discovery'
      tag_name: ${{ github.ref_name }}
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  build_and_push_accommodation_image:
    name: Accommodation image
    uses: ./.github/workflows/build-publish-image.yml
    with:
      context: 'back/accommodation-service'
      dockerfile: 'back/accommodation-service/Dockerfile'
      image_name: 'tripi-accommodation'
      tag_name: ${{ github.ref_name }}
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  build_and_push_activity_image:
    name: Activity image
    uses: ./.github/workflows/build-publish-image.yml
    with:
      context: 'back/activity-service'
      dockerfile: 'back/activity-service/Dockerfile'
      image_name: 'tripi-activity'
      tag_name: ${{ github.ref_name }}
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  build_and_push_bar_image:
    name: Bar image
    uses: ./.github/workflows/build-publish-image.yml
    with:
      context: 'back/bar-service'
      dockerfile: 'back/bar-service/Dockerfile'
      image_name: 'tripi-bar'
      tag_name: ${{ github.ref_name }}
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  build_and_push_restaurant_image:
    name: Restaurant image
    uses: ./.github/workflows/build-publish-image.yml
    with:
      context: 'back/restaurant-service'
      dockerfile: 'back/restaurant-service/Dockerfile'
      image_name: 'tripi-restaurant'
      tag_name: ${{ github.ref_name }}
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  build_and_push_transport_image:
    name: Transport image
    uses: ./.github/workflows/build-publish-image.yml
    with:
      context: 'back/transport-service'
      dockerfile: 'back/transport-service/Dockerfile'
      image_name: 'tripi-transport'
      tag_name: ${{ github.ref_name }}
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  build_and_push_trip_image:
    name: Trip image
    uses: ./.github/workflows/build-publish-image.yml
    with:
      context: 'back/trip-service'
      dockerfile: 'back/trip-service/Dockerfile'
      image_name: 'tripi-trip'
      tag_name: ${{ github.ref_name }}
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  build_and_push_auth_image:
    name: Auth image
    uses: ./.github/workflows/build-publish-image.yml
    with:
      context: 'back/auth-service'
      dockerfile: 'back/auth-service/Dockerfile'
      image_name: 'tripi-auth'
      tag_name: ${{ github.ref_name }}
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  build_and_push_user_image:
    name: User image
    uses: ./.github/workflows/build-publish-image.yml
    with:
      context: 'back/user-service'
      dockerfile: 'back/user-service/Dockerfile'
      image_name: 'tripi-user'
      tag_name: ${{ github.ref_name }}
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
