name: Build and publish API images

on:
  workflow_call:

jobs:
  build_and_push_gateway_image:
    uses: ./.github/workflows/build-publish-image.yml
    with:
      context: 'back/gateway'
      dockerfile: 'back/gateway/Dockerfile'
      image_name: 'tripi-gateway'
      tag_name: ${{ github.event.inputs.tag_name }}

  build_and_push_discovery_image:
    uses: ./.github/workflows/build-publish-image.yml
    with:
      context: 'back/discovery'
      dockerfile: 'back/discovery/Dockerfile'
      image_name: 'tripi-discovery'
      tag_name: ${{ github.event.inputs.tag_name }}

  build_and_push_accommodation_image:
    uses: ./.github/workflows/build-publish-image.yml
    with:
      context: 'back/accommodation'
      dockerfile: 'back/accommodation/Dockerfile'
      image_name: 'tripi-accommodation'
      tag_name: ${{ github.event.inputs.tag_name }}

  build_and_push_activity_image:
    uses: ./.github/workflows/build-publish-image.yml
    with:
      context: 'back/activity'
      dockerfile: 'back/activity/Dockerfile'
      image_name: 'tripi-activity'
      tag_name: ${{ github.event.inputs.tag_name }}

  build_and_push_bar_image:
    uses: ./.github/workflows/build-publish-image.yml
    with:
      context: 'back/bar'
      dockerfile: 'back/bar/Dockerfile'
      image_name: 'tripi-bar'
      tag_name: ${{ github.event.inputs.tag_name }}

  build_and_push_restaurant_image:
    uses: ./.github/workflows/build-publish-image.yml
    with:
      context: 'back/restaurant'
      dockerfile: 'back/restaurant/Dockerfile'
      image_name: 'tripi-restaurant'
      tag_name: ${{ github.event.inputs.tag_name }}

  build_and_push_transport_image:
    uses: ./.github/workflows/build-publish-image.yml
    with:
      context: 'back/transport'
      dockerfile: 'back/transport/Dockerfile'
      image_name: 'tripi-transport'
      tag_name: ${{ github.event.inputs.tag_name }}

  build_and_push_trip_image:
    uses: ./.github/workflows/build-publish-image.yml
    with:
      context: 'back/trip'
      dockerfile: 'back/trip/Dockerfile'
      image_name: 'tripi-trip'
      tag_name: ${{ github.event.inputs.tag_name }}

  build_and_push_auth_image:
    uses: ./.github/workflows/build-publish-image.yml
    with:
      context: 'back/auth'
      dockerfile: 'back/auth/Dockerfile'
      image_name: 'tripi-auth'
      tag_name: ${{ github.event.inputs.tag_name }}

  build_and_push_user_image:
    uses: ./.github/workflows/build-publish-image.yml
    with:
      context: 'back/user'
      dockerfile: 'back/user/Dockerfile'
      image_name: 'tripi-user'
      tag_name: ${{ github.event.inputs.tag_name }}

