name: Deploy on remote server

on:
  workflow_call:
    secrets:
        SERVER_USERNAME:
            description: 'Username of the server'
            required: true
        SERVER_IP:
            description: 'IP of the server'
            required: true
        SERVER_SSH_KEY:
            description: 'SSH key of the server'
            required: true

jobs:
  deploy:
    name: Deploy on remote server
    runs-on: ubuntu-latest
    steps:
      - name: Execute script to setup docker-compose architecture
        uses: appleboy/ssh-action@master
        with:
          username: ${{ secrets.SERVER_USERNAME }}
          host: ${{ secrets.SERVER_IP }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          script: |
            cd /app/ && sh ./deploy.sh