name: Run App tests

on:
  workflow_call:

jobs:
  run_app_tests:
    name: Run App tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 19.x
        uses: actions/setup-node@v1
        with:
          node-version: 19.x

      - name: Install front dependencies
        working-directory: ./front
        run: npm ci

      - name: Run tests
        working-directory: ./front
        run: npm run test:prod